Update tr.json
fnbrco/translations pull request #138
Opened 2021-01-20 22:28 UTC by Melocet

- forgotten lines

2021-01-20 23:10 UTC, Joachiem commented on tr.json
> +            "error-ratelimit" : "Çok fazla istek, lütfen birkaç dakika sonra tekrar deneyin",
Remove the comma at the end of this line to comply with the JSON format.

2021-01-20 23:10 UTC, Joachiem requested changes
Just a little comma that needs to be removed :)

2021-01-21 08:24 UTC, Melocet reviewed
thankies

2021-01-25 12:28 UTC, Joachiem approved these changes

2021-01-25 12:28 UTC, merged